import { useTheme } from "@/lib/theme";

// Generated by scripts/generate-assets.ts from assets-src/ — keep in sync.
const BANNERS = {
  dark: { name: "banner-dark", width: 1600, height: 583 },
  light: { name: "banner-light", width: 1600, height: 479 },
} as const;

/**
 * Theme-aware demo banner. Rendered conditionally from the theme context so
 * only the active theme's image is fetched (a CSS dark:hidden toggle downloads
 * both). Only mounts client-side mid-demo, so there is no hydration risk.
 */
export function ThemeBanner() {
  const { theme } = useTheme();
  const banner = BANNERS[theme];
  const base = import.meta.env.BASE_URL;
  return (
    <picture>
      <source type="image/webp" srcSet={`${base}${banner.name}.webp`} />
      <img
        src={`${base}${banner.name}.png`}
        alt="Server events banner"
        width={banner.width}
        height={banner.height}
        loading="lazy"
        decoding="async"
        className="h-auto w-full"
      />
    </picture>
  );
}
